rentalcars/config/routes.rb
  Rails.application.routes.draw do
  get 'requests/new'

  get 'cars/new'
  get 'cars/show'
  get 'cars/edit'
  get 'cars/update'
  get 'cars/destroy'
  get 'cars/search'

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'users/new'
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/password_create', to: 'users#password_create'
  resources :users 
  resources :cars
  resources :searches
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :requests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rentalcars/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @cars = Car.paginate(page: params[:page])
    if logged_in?
    @requests = current_user.requests.where(["status LIKE ? ", -1])
    @cars = Array.new
    @date = Array.new
    @requests.each {|b| @cars << Car.find_by(id: b.car_id)} 
    end
  end
  def help
  end

  def about
  end

  def contact
  end
end

rentalcars/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

rentalcars/app/views/static_pages/_admin.html.erb
<h1>Tất cả các yêu cầu</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nhãn hiệu</th>
      <th>Đời xe</th>
      <th>User</th>
      <th>Ngày nhận</th>
      <th>Ngày trả</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% get_requestcar.each do |e| %>
      <tr>
        <td><%= Car.find_by(id: e.car_id).brand%></td>
        <td><%= Car.find_by(id: e.car_id).model %></td>
        <td><%= User.find_by(id: e.user_id).name %></td>
        <td><%= e.pickup %></td>
        <td><%= e.dropoff%></td>
        <%= render 'shared/approve', object: e %>
        <%= render 'shared/deny',    object: e%>
      </tr>
    <% end %>
  </tbody>
</table>    

rentalcars/app/views/static_pages/_user.html.erb
<div> 
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>  
</div>
<div class="container">
    <div class="col-md-6">
        <h1>Xe đang thuê</h1>
        <table class="table table-hover">
        <thead>
            <tr>
              <th>User id</th>
              <th>Ngày nhận</th>
              <th>Ngày trả</th>
              <th>Status</th>
              <th>Đã thuê</th>
              <th>Car id</th>
            </tr>
        </thead>
        <%= render 'requests/now' %>
        </table> 
    </div>
    
    <div class="col-md-6">
        <h1>Lịch sử thuê xe</h1>
        <table class="table table-hover">
        <thead>
            <tr>
              <th>User id</th>
              <th>Ngày nhận</th>
              <th>Ngày trả</th>
              <th>Status</th>
              <th>Đã thuê</th>
              <th>Car id</th>
            </tr>
        </thead>
        <%= render 'requests/history' %>
        </table> 
    </div>
</div>

rentalcars/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  About Viet Hoc Le
  <a href="https://www.facebook.com/viethocpro">about page</a>.
</p>

rentalcars/app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact Viet Hoc Le
  <a href="https://www.facebook.com/viethocpro">contact page</a>.
</p>

rentalcars/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  If you need help frome Viet Hoc Le
  <a href="https://www.facebook.com/viethocpro">Help page</a>.
</p>

rentalcars/app/views/static_pages/home.html.erb
<% if logged_in? %>
    <% if current_user.admin? %>
      <%= render 'admin' %>
    <% else %>
      <%= render 'user'%>
    <% end %>
    
<% else %>
<div class="center jumbotron" id="background_image">
  <h1>Welcome to Rentalcars DaNang</h1>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<div >
	<h1>Listing Cars</h1>
    <%= form_tag cars_search_path, :method => 'get'  do %>
   	<%= text_field_tag :search, params[:search]%>
    <%= submit_tag "Search" %>
	<% end %>	
	<%= link_to "Advanced Search" , new_search_path %>
</div>
<div class="cars">
   <%= render @cars%>
</div>
<% end %>