rentalcars/config/routes.rb
  Rails.application.routes.draw do
  get 'requests/new'

  get 'cars/new'
  get 'cars/show'
  get 'cars/edit'
  get 'cars/update'
  get 'cars/destroy'
  get 'cars/search'

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'users/new'
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/password_create', to: 'users#password_create'
  resources :users 
  resources :cars
  resources :searches
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :requests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rentalcars/app/models/car.rb
class Car < ApplicationRecord
	has_many :requests
	def self.search(search)
     if search
        where(["brand LIKE ?", "%#{search}%"])
     else
       all
     end
   	end

  	def handing_car(car_id)
   		update_columns(pickup: Request.where(["car_id = ?", car_id]).first.pickup)
   		update_columns(dropoff: Request.where(["car_id = ?", car_id]).first.dropoff)
   	end
    def cancel_car
      update_columns(pickup: nil)
      update_columns(dropoff: nil)
    end
end

rentalcars/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :admin_user,     only: :destroy
  def new
    @car = Car.new
  end
  def search
   @cars = Car.search(params[:search]).paginate(page: params[:page])
 end
   
  def create
    @car = Car.new(car_params)
    if @car.save
      flash[:info] = "Done Creat New Car!"
      render 'show'
    else
      render 'new'
    end
  end

  def index
    @cars = Car.paginate(page: params[:page])
  end

  def show
    session[:car_id] = params[:id].to_i
    @car = Car.find(params[:id])
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    if @car.update_attributes(car_params)
       flash[:success] = "Car updated"
      redirect_to 
    else
      render 'edit'
    end
  end
  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end

  def destroy
    Car.find(params[:id]).destroy
    flash[:succes] = "Car deleted"
    redirect_to cars_url
  end

  private

    def car_params
      params.require(:car).permit(:isCar, :brand, :model, :price, :seat, :about, :pickup, :dropoff)
    end

    # Before filters

    # def get_vehicle
    #   @vehicle = vehicle.find_by(email: params[:email])
    # end

end

rentalcars/app/helpers/cars_helper.rb
module CarsHelper
    def current_car
        Car.find(session[:car_id])
    end
end

rentalcars/app/views/cars/_car.html.erb
<div>
	<div class="col-sm-4">
	   <h1>Nhãn hiệu:<%= link_to car.brand, car %></h1>
	   <h3>Đời xe (Model):<%= link_to car.model, car %></h3>
	   <h3>Số chỗ:<%= link_to car.seat, car %> </h3>
	   <h3>Đơn giá (/ngày):<%= link_to car.price, car %> VND </h3>
	   <h3>Chi tiết:<%= link_to car.about, car %> </h3>
	   <% if logged_in? %>
   			<% if current_user.admin? && !current_user?(@user) %>	
        <%else%>
        	<%= link_to("Đặt thuê ngay", new_request_path(car: car.id) , class: "btn btn-primary")%>
       	<%end %>
       	<%else %> 
       		<%= link_to("Đặt thuê ngay", new_request_path(car: car.id) , class: "btn btn-primary")%>
       	<% end %>
   	</br>
   	<% if logged_in? %>
   		<% if current_user.admin? && !current_user?(@user) %>
	        <%= link_to "Delete", car, method: :delete, class: "btn btn-primary",
	                                      data: { confirm: "You sure?" } %>
	        <%= link_to "Update", edit_car_path(car), class: "btn btn-primary" %>	
        <% end %>
    <% end %>
    </div>
</div>

rentalcars/app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <%= render 'shared/error_messages', object: @car %>
  <%= f.label "Loại xe:" %>
	<select name="car[isCar]">
	 <option value="Ô tô">Ô tô</option>
	 <option value="Xe máy">Xe máy</option>
	</select>

 <%= f.label "Nhãn hiệu:" %>
  <%= f.text_field :brand, class: 'form-control' %>

 <%= f.label "Đời xe (Model):" %>
  <%= f.text_field :model, class: 'form-control' %>

 <%= f.label "Đơn giá (/ngày):"%>
  <%= f.number_field :price, class: 'form-control' %>
  

 <%= f.label "Số chỗ:" %>
  <%= f.number_field :seat, class: 'form-control' %>
  

 <%= f.label "Chi tiết:" %>
  <%= f.text_area :about, class: 'form-control' %>

 <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

rentalcars/app/views/cars/edit.html.erb
<% provide(:title, 'Edit car') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update Car Information</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

rentalcars/app/views/cars/index.html.erb
<% provide(:title, 'All car') %>
<%= link_to "Creat New Car", new_car_path, class: "btn btn-lg btn-primary" %>
<h1>Tất cả xe</h1>

<%= will_paginate %>

<ul class="cars">
   <%= render @cars %>
</ul>

<%= will_paginate %>

rentalcars/app/views/cars/new.html.erb
<% provide(:title, 'newcar') %>
<% provide(:button_text, 'Create new car') %>
<h1>Create</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

rentalcars/app/views/cars/search.html.erb
<% provide(:title, 'Result') %>
<h1>Kết quả tìm kiếm</h1>

<%= will_paginate %>

<div class="cars">
    <%= render @cars %>
</div>

<%= will_paginate %>

rentalcars/app/views/cars/show.html.erb
<% provide(:title, @car.model) %>
<% if logged_in? %>
   		<% if current_user.admin? && !current_user?(@user) %>
	       <%= link_to "Creat New Car", new_car_path, class: "btn btn-lg btn-primary" %>
        <% end %>
<% end %>
<div class="row">
    <h1>Nhãn hiệu:<%= @car.brand%></h1>
	<h3>Đời xe (Model):<%= @car.model %></h3>
	<h3>Số chỗ:<%= @car.seat %> </h3>
	<h3>Đơn giá (/ngày)<%= @car.price %> VND </h3>
	<h3>Chi tiết:<%= @car.about %></h3>
</div>
<h1>Listing Cars</h1>
<%= form_tag cars_path, :method => 'get'  do %>
<%= text_field_tag :search, params[:search]%>
<%= submit_tag "Search" %>
<%= link_to "Advanced Search" , new_search_path %>
<% end %>