rentalcars/config/routes.rb
  Rails.application.routes.draw do
  get 'requests/new'

  get 'cars/new'
  get 'cars/show'
  get 'cars/edit'
  get 'cars/update'
  get 'cars/destroy'
  get 'cars/search'

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'users/new'
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/password_create', to: 'users#password_create'
  resources :users 
  resources :cars
  resources :searches
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :requests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rentalcars/app/models/user.rb
class User < ActiveRecord::Base
  has_many :requests, dependent: :destroy
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_secure_password
  
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

rentalcars/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  before_action :get_user, only: :password_create
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    
    @cars = Car.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:succes] = "User deleted"
    redirect_to users_url
  end

  def password_create
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'create_password'
    elsif @user.update_attributes(password_params)
      log_in @user
      @user.update_attribute(:activated, true)
      @user.update_attribute(:activated_at, Time.zone.now)
      flash[:success] = "Password has been created"
      redirect_to @user
    else
      render 'create_password'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email: params[:email])
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user? @user
    end

    def admin_user
      redirect_to root_url unless current_user.admin?
    end

    
end

rentalcars/app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

rentalcars/app/views/users/_car.html.erb
<li>
   <%= link_to car.brand, car %>
   <%= link_to car.model, car %>
   <%= link_to car.seat, car %> 
   <%= link_to car.price, car %> 
   <%= link_to car.about, car %> 
   <%= link_to "Request" , request_new_path %>

</li>

rentalcars/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

rentalcars/app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user)%>
		| <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure ?" } %>
	<% end %>
</li>

rentalcars/app/views/users/create_password.html.erb
<% provide(:title, "Create password") %>
<h1>Create password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_create_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

rentalcars/app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

rentalcars/app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1>All users</h1>

<%= will_paginate %>

<div class="users">
	<%= render @users %>
</div>

<%= will_paginate %>

rentalcars/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

rentalcars/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>
<% if logged_in? %>
    <% if current_user.admin? %>
      <h1>Giao dịch</h1>
      <div class="col-md-6">
        <h1>Cho thuê</h1  >
        <table class="table table-hover">
        <thead>
            <tr>
              <th>User id</th>
              <th>Ngày nhận</th>
              <th>Ngày trả</th>
              <th>Status</th>
              <th>Chưa thuê</th>
              <th>Car id</th>
              <th>Action</th>
            </tr>
        </thead>
        <%= render 'requests/request'%>
        </table> 
      </div>
      <div class="col-md-6">
        <h1>Đang thuê</h1>
        <table class="table table-hover">
        <thead>
            <tr>
              <th>User id</th>
              <th>Ngày nhận</th>
              <th>Ngày trả</th>
              <th>Status</th>
              <th>Đang thuê</th>
              <th>Car id</th>
              <th>Action</th>
            </tr>
        </thead>
        <%= render 'requests/rental'%>
        </table> 
      </div>
    <% else %>
      <h1>Listing Cars</h1>
      <%= form_tag cars_search_path, :method => 'get'  do %>
        <%= text_field_tag :search, params[:search]%>
        <%= submit_tag "Search" %>
      <% end %>
      <%= link_to "Advanced Search" , new_search_path %>
      <% provide(:title, 'All car') %>
      <ul class="cars">
          <%= render @cars%>
      </ul>
    <% end %>
<% end %>
	
  